version: "3.9"

services:
  app:
    image: milonhossain32/kalman_backend_app:latest
    build:
      context: .
      
    container_name: kalman_backend_app
    ports:
      - "5000:5000"
    environment:
      .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: kalman_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
