name: "setup-and-load-env"
description: "setup-and-load-env composite action"
inputs:
  DATABASE_URL:
    description: "DATABASE_URL from .env.production"
    required: true
  SALT_ROUND:
    description: "SALT_ROUND from .env.production"
    required: true
  ACCESS_TOKEN_SECRET:
    description: "ACCESS_TOKEN_SECRET from .env.production"
    required: true
  REFRESH_TOKEN_SECRET:
    description: "REFRESH_TOKEN_SECRET from .env.production"
    required: true
  ACCESS_TOKEN_EXPIREIN:
    description: "ACCESS_TOKEN_EXPIREIN from .env.production"
    required: true
  REFRESH_TOKEN_EXPIREIN:
    description: "REFRESH_TOKEN_EXPIREIN from .env.production"
    required: true
  EMAIL_USER:
    description: "EMAIL_USER from .env.production"
    required: true
  EMAIL_PASS:
    description: "EMAIL_PASS from .env.production"
    required: true
  SMTP_HOST:
    description: "SMTP_HOST from .env.production"
    required: true
  SMPT_PORT:
    description: "SMPT_PORT from .env.production"
    required: true
  SMPT_FROM:
    description: "SMPT_FROM from .env.production"
    required: true
  ADMIN_EMAIL:
    description: "ADMIN_EMAIL from .env.production"
    required: true
  ADMIN_PASSWORD:
    description: "ADMIN_PASSWORD from .env.production"
    required: true
  ADMIN_PHONE:
    description: "ADMIN_PHONE from .env.production"
    required: true
  CLIENT_URL:
    description: "CLIENT_URL from .env.production"
    required: true
  SERVER_URL:
    description: "SERVER_URL from .env.production"
    required: true
  STRIPE_SECRET_KEY:
    description: "STRIPE_SECRET_KEY from .env.production"
    required: true
  STRIPE_ADMIN_ID:
    description: "STRIPE_ADMIN_ID from .env.production"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate .env
      shell: bash
      run: |
        ENV_FILE="$GITHUB_WORKSPACE/.env"
        {
          echo "DATABASE_URL=${{ inputs.DATABASE_URL }}"
          echo "SALT_ROUND=${{ inputs.SALT_ROUND }}"
          echo "ACCESS_TOKEN_SECRET=${{ inputs.ACCESS_TOKEN_SECRET }}"
          echo "REFRESH_TOKEN_SECRET=${{ inputs.REFRESH_TOKEN_SECRET }}"
          echo "ACCESS_TOKEN_EXPIREIN=${{ inputs.ACCESS_TOKEN_EXPIREIN }}"
          echo "REFRESH_TOKEN_EXPIREIN=${{ inputs.REFRESH_TOKEN_EXPIREIN }}"
          echo "EMAIL_USER=${{ inputs.EMAIL_USER }}"
          echo "EMAIL_PASS=${{ inputs.EMAIL_PASS }}"
          echo "SMTP_HOST=${{ inputs.SMTP_HOST }}"
          echo "SMPT_PORT=${{ inputs.SMPT_PORT }}"
          echo "SMPT_FROM=${{ inputs.SMPT_FROM }}"
          echo "ADMIN_EMAIL=${{ inputs.ADMIN_EMAIL }}"
          echo "ADMIN_PASSWORD=${{ inputs.ADMIN_PASSWORD }}"
          echo "ADMIN_PHONE=${{ inputs.ADMIN_PHONE }}"
          echo "CLIENT_URL=${{ inputs.CLIENT_URL }}"
          echo "SERVER_URL=${{ inputs.SERVER_URL }}"
          echo "STRIPE_SECRET_KEY=${{ inputs.STRIPE_SECRET_KEY }}"
          echo "STRIPE_ADMIN_ID=${{ inputs.STRIPE_ADMIN_ID }}"
        } > "$ENV_FILE"
        if [[ -n "${{ inputs.VPS_SSH_PRIVATE_KEY }}" ]]; then
          echo "${{ inputs.VPS_SSH_PRIVATE_KEY }}" > "$GITHUB_WORKSPACE/deploy_key.pem"
          chmod 600 "$GITHUB_WORKSPACE/deploy_key.pem"
          echo "VPS_SSH_PRIVATE_KEY_FILE=$GITHUB_WORKSPACE/deploy_key.pem" >> "$ENV_FILE"
        fi
